// Auto-generated by export_rules.py from rules_default.yaml. Do not edit by hand.
const RULES = {
  "key_patterns": [
    "password",
    "passwd",
    "pwd",
    "secret",
    "token",
    "api[_-]?key",
    "apikey",
    "access[_-]?key",
    "private[_-]?key",
    "client[_-]?secret",
    "auth",
    "credential",
    "connection[_-]?string",
    "conn[_-]?str",
    "jdbc",
    "datasource\\.url",
    "db\\.url",
    "db\\.host",
    "db\\.password",
    "db\\.username",
    "host",
    "hostname",
    "ip[_-]?address",
    "endpoint",
    "url",
    "uri",
    "ssn",
    "encryption[_-]?key",
    "signing[_-]?key",
    "session[_-]?key",
    "cert",
    "keystore",
    "truststore"
  ],
  "value_patterns": [
    {
      "name": "ipv4_address",
      "regex": "\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b"
    },
    {
      "name": "ipv6_address",
      "regex": "\\b([0-9a-fA-F]{1,4}:){2,7}[0-9a-fA-F]{1,4}\\b"
    },
    {
      "name": "url_with_credentials",
      "regex": "[a-zA-Z][a-zA-Z0-9+.-]*://[^\\s:/@]+:[^\\s:/@]+@[^\\s\"']+"
    },
    {
      "name": "generic_url",
      "regex": "(https?|ftp|jdbc:[a-z]+|mongodb(\\+srv)?|redis|amqp)://[^\\s\"']+"
    },
    {
      "name": "aws_access_key_id",
      "regex": "\\bAKIA[0-9A-Z]{16}\\b"
    },
    {
      "name": "aws_secret_key_assignment",
      "regex": "(?i)aws_secret_access_key[\"']?\\s*[:=]\\s*[\"']?[A-Za-z0-9/+=]{40}"
    },
    {
      "name": "github_token",
      "regex": "\\bgh[pousr]_[A-Za-z0-9]{36}\\b"
    },
    {
      "name": "slack_token",
      "regex": "\\bxox[baprs]-[A-Za-z0-9-]{10,}\\b"
    },
    {
      "name": "jwt_token",
      "regex": "\\beyJ[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+\\b"
    },
    {
      "name": "bearer_token",
      "regex": "(?i)bearer\\s+([A-Za-z0-9\\-._~+/]{20,}=*)"
    },
    {
      "name": "private_key_block",
      "regex": "-----BEGIN [A-Z ]*PRIVATE KEY-----[\\s\\S]+?-----END [A-Z ]*PRIVATE KEY-----"
    },
    {
      "name": "email_address",
      "regex": "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}\\b"
    }
  ],
  "code_patterns": {
    "java": [
      "(?i)(?:String|final\\s+String)\\s+\\w*(?:password|secret|token|apikey|api_key|key|credential|auth)\\w*\\s*=\\s*\"([^\"]*)\""
    ],
    "python": [
      "(?i)\\w*(?:password|secret|token|apikey|api_key|key|credential|auth)\\w*\\s*=\\s*[\"']([^\"']*)[\"']",
      "(?i)(?:os\\.getenv|os\\.environ\\.get)\\(\\s*[\"'][^\"']*(?:password|secret|token|apikey|api_key|key|credential|auth)[^\"']*[\"']\\s*,\\s*[\"']([^\"']*)[\"']\\s*\\)"
    ],
    "javascript": [
      "(?i)(?:const|let|var)\\s+\\w*(?:password|secret|token|apikey|api_key|key|credential|auth)\\w*\\s*(?::\\s*[^=;\\n]+?)?\\s*=\\s*[`\"'](.*?)[`\"']"
    ],
    "go": [
      "(?i)\\w*(?:password|secret|token|apikey|api_key|key|credential|auth)\\w*\\s*:?=\\s*\"([^\"]*)\""
    ],
    "csharp": [
      "(?i)(?:string|var)\\s+\\w*(?:password|secret|token|apikey|api_key|key|credential|auth)\\w*\\s*=\\s*\"([^\"]*)\""
    ]
  },
  "placeholder_allowlist": [
    "changeme",
    "change_me",
    "your_api_key_here",
    "your-api-key-here",
    "yourapikeyhere",
    "example",
    "dummy",
    "placeholder",
    "xxxxxxxx",
    "test123",
    "localhost",
    "127.0.0.1",
    "0.0.0.0",
    "none",
    "null",
    "n/a",
    "todo",
    "fixme",
    "insert_secret_here",
    "your_bearer_token_here"
  ]
};

if (typeof window !== "undefined") {
  window.RULES = RULES;
}

if (typeof module !== "undefined") {
  module.exports = RULES;
}
